# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-ecom"
client_id = "fe263143b9358d60b6a7c8f90b0b071e"
application_url = "https://milton-notes-players-throwing.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_product_listings, write_shipping"

[auth]
redirect_urls = [
  "https://milton-notes-players-throwing.trycloudflare.com/auth/callback",
  "https://milton-notes-players-throwing.trycloudflare.com/auth/shopify/callback",
  "https://milton-notes-players-throwing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "smart-phone-vn.myshopify.com"
